/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ritvik.keyemulator;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;

/**
 *
 * @author Ritvik
 */
public class Launcher extends javax.swing.JFrame {

    /**
     * Creates new form Launcher
     */
    public Launcher() {
        initComponents();
        try {
            vRobo = new Robot();
        } catch (AWTException ex) {
            System.exit(-1);
        }
        this.pack();
        this.action();
    }
    
    private boolean started=false;
    Thread vThread = null;
    Robot vRobo = null;
    Integer vSec = 90;
    private static final String START = "<html><p style='color:#00dd00'>&#x25B6;</p></html>"; //"start";
    private static final String STOP  = "<html><p style='color:#ff0000'>&#x23F9;</p></html>"; //"stop";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vTimer = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        vButton = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prevent Screen Timeout");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(200, 200));
        setUndecorated(true);
        setResizable(false);

        vTimer.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        vTimer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        vTimer.setText("90");
        vTimer.setMaximumSize(new java.awt.Dimension(100, 15));
        vTimer.setMinimumSize(new java.awt.Dimension(20, 15));
        vTimer.setPreferredSize(new java.awt.Dimension(20, 15));

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Prevent Screen Timeout When Idle");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        vButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vButton.setText(START);
        vButton.setMaximumSize(new java.awt.Dimension(20, 15));
        vButton.setMinimumSize(new java.awt.Dimension(20, 15));
        vButton.setPreferredSize(new java.awt.Dimension(20, 15));
        vButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(vButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(vButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Time in Seconds");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vButtonMouseClicked
        // TODO add your handling code here:
        action();
    }//GEN-LAST:event_vButtonMouseClicked

    private void action(){
        new Thread(() -> {
            vButton.setEnabled(false);
        
            if(vButton.getText().equals(START)){
                
                vTimer.setEnabled(false);
                vThread = new Thread(() -> {
                    
                    while(started){
                        try {
                            int timer = vSec;
                            try{
                                timer = Integer.parseInt(vTimer.getText());
                                if(timer<=0) timer=vSec;
                            }
                            catch(Exception e){
                                timer=vSec;
                            }
                            vSec=timer;
                            while(timer>0 && started){
                                timer--;
                                vTimer.setText(timer+"");
                                Thread.sleep(1000);
                            }
                            vRobo.keyPress(KeyEvent.VK_F23);
                            //vRobo.keyPress(KeyEvent.VK_SEMICOLON);

                        } catch (InterruptedException ex) {
                            
                        }
                    }
                });

                vButton.setText(STOP);
                try{
                    this.setOpacity(0.5f);
                }
                catch(Exception e){
                    System.err.println("Unable to update Opacity for Window");
                }
                started=true;
                vThread.start();
                try{
                    Launcher.this.setState(JFrame.ICONIFIED);
                }
                catch(Exception e){
                    System.err.println("Unable to minimize the Window");
                }
                
            }
            else{
                
                vButton.setText(START);
                try{
                    this.setOpacity(0.9f);
                }
                catch(Exception e){
                    System.err.println("Unable to update Opacity for Window");
                }
                vTimer.setText(vSec+"");
                vTimer.setEnabled(true);
                started=false;
                
                try {
                    vThread.join();
                } catch (InterruptedException ex) {
                
                }
            }
            
            vButton.setEnabled(true);
            
        }).start();
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Launcher().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel vButton;
    private javax.swing.JTextField vTimer;
    // End of variables declaration//GEN-END:variables
}
